export const menProducts = [
    {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/men-tshirt-1.jpg",
        price: 19.99,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        sign: '#212465',
        category: 'men',
        block: 'selected-1',
    },
    {
        id: 2,
        title: "Loose Knit 3/4 Sleeve",
        img: "img/men-tshirt-2.png",
        price: 59.99,
        info: "Loose Knit 3/4 Sleeve in the uiKit line with a colorful print. Made of jersey cotton. Loose fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        sign: '#342235',
        category: 'men',
        block: 'selected-2',
    },
    {
        id: 3,
        title: "Basic Slim Fit T-Shirt",
        img: "img/men-tshirt-3.png",
        price: 19.99,
        info: "Basic Slim Fit T-Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        sign: '#124791',
        category: 'men',
        block: 'selected-3',
    },
    {
        id: 4,
        title: "Oxford Dress Shirt",
        img: "img/men-tshirt-4.png",
        price: 39.99,
        info: "Oxford Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        }, 
        inCart: false,
        count: 0,
        total: 0,
        sign: '#482319',
        category: 'women',
        block: 'selected-4',
    },
    {
        id: 5,
        title: "Premium Dress Shirt",
        img: "img/men-tshirt-5.png",
        price: 59.99,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        sign: '#619371',
        category: 'women',
        block: 'today-1',
    },
    {
        id: 6,
        title: "Patterned Dress Shirt",
        img: "img/men-tshirt-6.png",
        price: 49.99,
        info: "Patterned Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        sign: '#481236',
        category: 'women',
        block: 'today-2',
    },
    
];

export const detailProduct = {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/men-tshirt-1-details.png",
        price: 19.99,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
    };
    