export const menProducts = [
    {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/men-tshirt-1.jpg",
        price: 19.99,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#217736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'selected-1',
    },
    {
        id: 2,
        title: "Loose Knit 3/4 Sleeve",
        img: "img/men-tshirt-2.png",
        price: 59.99,
        info: "Loose Knit 3/4 Sleeve in the uiKit line with a colorful print. Made of jersey cotton. Loose fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#218736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'selected-2',
    },
    {
        id: 3,
        title: "Basic Slim Fit T-Shirt",
        img: "img/men-tshirt-3.png",
        price: 19.99,
        info: "Basic Slim Fit T-Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#219736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        
    },
    {
        id: 4,
        title: "Oxford Dress Shirt",
        img: "img/men-tshirt-4.png",
        price: 39.99,
        info: "Oxford Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        }, 
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#220736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'selected-4',
    },
    {
        id: 5,
        title: "Premium Dress Shirt",
        img: "img/men-tshirt-5.png",
        price: 59.99,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#221736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'today-1',
    },
    {
        id: 6,
        title: "Patterned Dress Shirt",
        img: "img/men-tshirt-6.png",
        price: 49.99,
        info: "Patterned Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        block: 'today-2',
        identifier: '#222736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },

    // Polo Men

    {
        id: 7,
        title: "Patterned Dress Polo",
        img: "img/polo-man-1.jpeg",
        price: 49.95,
        info: "Patterned Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#721236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'new',
    },
    {
        id: 8,
        title: "River Island waffle polo",
        img: "img/polo-man-2.jpeg",
        price: 69.95,
        info: "River Island waffle polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#722236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 9,
        title: "Muscle fit jersey polo",
        img: "img/polo-man-3.jpeg",
        price: 45.95,
        info: "Muscle fit jersey polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#723236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 10,
        title: "Long sleeve tipped polo",
        img: "img/polo-man-4.jpeg",
        price: 52.95,
        info: "Long sleeve tipped polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#724236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 11,
        title: "Tonal batwing logo pique polo",
        img: "img/polo-man-5.jpeg",
        price: 33.95,
        info: "Tonal batwing logo pique polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#725236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 12,
        title: "Selected Homme polo shirt",
        img: "img/polo-man-6.jpeg",
        price: 38.95,
        info: "Selected Homme polo shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#726236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 13,
        title: "Crooked Tongues rugby polo",
        img: "img/polo-man-7.jpeg",
        price: 55.95,
        info: "Crooked Tongues rugby polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#727236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 14,
        title: "Fred Perry bomber collar polo",
        img: "img/polo-man-8.jpeg",
        price: 45.95,
        info: "Fred Perry bomber collar polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#728236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
        block: 'selected-3',
    },
    {
        id: 15,
        title: "Selected Homme knitted polo",
        img: "img/polo-man-9.jpeg",
        price: 75.95,
        info: "Selected Homme knitted polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#729236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },

    // Shirts Men

    {
        id: 16,
        title: "Selected Homme knitted shirt",
        img: "img/shirt-man-1.jpeg",
        price: 35.95,
        info: "Selected Homme knitted shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#491832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 17,
        title: "Relaxed revere windowpane shirt",
        img: "img/shirt-man-2.jpeg",
        price: 38.95,
        info: "Relaxed revere windowpane shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#492832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 18,
        title: "Stretch skinny fit shirt",
        img: "img/shirt-man-3.jpeg",
        price: 69.95,
        info: "Stretch skinny fit shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#493832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 19,
        title: "Revere slub cotton shirt",
        img: "img/shirt-man-4.jpeg",
        price: 29.95,
        info: "Revere slub cotton shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#494832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 20,
        title: "Stretch slim fit work shirt",
        img: "img/shirt-man-5.jpeg",
        price: 49.95,
        info: "Stretch slim fit work shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#495832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 21,
        title: "Selected Homme organic cotton grandad",
        img: "img/shirt-man-6.jpeg",
        price: 42.95,
        info: "Selected Homme organic cotton grandad cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#496832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 22,
        title: "Skinny fit stripe shirt in navy",
        img: "img/shirt-man-7.jpeg",
        price: 38.95,
        info: "Skinny fit stripe shirt in navy cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#497832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 23,
        title: "Weekday Marwin Nylon short sleeve",
        img: "img/shirt-man-8.jpeg",
        price: 25.95,
        info: "Weekday Marwin Nylon short sleeve cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#498832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 24,
        title: "New Look long sleeve poplin shirt",
        img: "img/shirt-man-9.jpeg",
        price: 42.95,
        info: "New Look long sleeve poplin shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#499832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },

    // Sweaters

    {
        id: 25,
        title: "Knitted wide rib turtle sweate",
        img: "img/sweater-man-1.jpeg",
        price: 62.95,
        info: "Knitted wide rib turtle sweate cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#541832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 26,
        title: "Knitted wide-rib turtleneck sweater",
        img: "img/sweater-man-2.jpeg",
        price: 69.95,
        info: "Knitted wide-rib turtleneck sweater in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#542832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 27,
        title: "Selected Homme sweater in white",
        img: "img/sweater-man-3.jpeg",
        price: 49.95,
        info: "Selected Homme sweater in white in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#543832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 28,
        title: "Jack & Jones Essentials sweater",
        img: "img/sweater-man-4.jpeg",
        price: 65.95,
        info: "Jack & Jones Essentials sweater in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#544832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 29,
        title: "Muscle fit ribbed sweater in black",
        img: "img/sweater-man-5.jpeg",
        price: 35.95,
        info: "Muscle fit ribbed sweater in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#545832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 30,
        title: "River Island ribbed sweater",
        img: "img/sweater-man-6.jpeg",
        price: 45.95,
        info: "River Island ribbed sweater in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#546832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 31,
        title: "New Look crew neck sweater",
        img: "img/sweater-man-7.jpeg",
        price: 75.95,
        info: "New Look crew neck sweater in dark gray in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#547832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 32,
        title: "Knitted oversized textured yarn",
        img: "img/sweater-man-8.jpeg",
        price: 39.95,
        info: "Knitted oversized textured yarn in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#548832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 33,
        title: "River Island long sleeve knitted",
        img: "img/sweater-man-9.jpeg",
        price: 38.95,
        info: "River Island long sleeve knitted in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#549832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },

// Overalls Man

    {
        id: 34,
        title: "One Above Another denim jumpsuit",
        img: "img/overall-man-1.jpeg",
        price: 68.95,
        info: "One Above Another denim jumpsuit in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#511637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 35,
        title: "Denim short boilersuit in blue",
        img: "img/overall-man-2.jpeg",
        price: 79.95,
        info: "Denim short boilersuit in blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#512637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 36,
        title: "Denim overalls in dusky pink",
        img: "img/overall-man-3.jpeg",
        price: 49.95,
        info: "Denim overalls in dusky pink in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#513637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 37,
        title: "Boilersuit in blue with pocket",
        img: "img/overall-man-4.jpeg",
        price: 59.95,
        info: "Boilersuit in blue with pocket in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#514637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 38,
        title: "Topman overalls in washed blue",
        img: "img/overall-man-5.jpeg",
        price: 54.95,
        info: "Topman overalls in washed blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#515637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 39,
        title: "Tall short boilersuit with cut",
        img: "img/overall-man-6.jpeg",
        price: 34.95,
        info: "Tall short boilersuit with cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#516637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 40,
        title: "Skinny overalls in black",
        img: "img/overall-man-7.jpeg",
        price: 64.95,
        info: "Skinny overalls in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#517637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 41,
        title: "Baggy denim overall in stone",
        img: "img/overall-man-8.jpeg",
        price: 59.95,
        info: "Baggy denim overall in stone in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#518637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 42,
        title: "Denim overalls in indigo length",
        img: "img/overall-man-9.jpeg",
        price: 51.95,
        info: "Denim overalls in indigo length in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#519637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },


];


export const detailProduct = {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/men-tshirt-1-details.png",
        price: 19.99,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
    };
    