export const menProducts = [
    
    // =====================================================================================
    //                    **********    Men's Products ***********
    // =====================================================================================



    // ================================================
    // T-shirts Men
    // ================================================
    
    {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/tshirt-man-1.jpeg",
        price: 19.95,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#211736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'selected-1',
    },
    {
        id: 2,
        title: "Loose Knit 3/4 Sleeve",
        img: "img/tshirt-man-2.jpeg",
        price: 29.95,
        info: "Loose Knit 3/4 Sleeve in the uiKit line with a colorful print. Made of jersey cotton. Loose fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#212736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        
    },
    {
        id: 3,
        title: "Basic Slim Fit T-Shirt",
        img: "img/tshirt-man-3.jpeg",
        price: 25.95,
        info: "Basic Slim Fit T-Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#213736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        
    },
    {
        id: 4,
        title: "Oxford Dress Shirt",
        img: "img/tshirt-man-4.jpeg",
        price: 22.95,
        info: "Oxford Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        }, 
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#214736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
        block: 'selected-4',
    },
    {
        id: 5,
        title: "Premium Dress Shirt",
        img: "img/tshirt-man-5.jpeg",
        price: 31.95,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#215736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 6,
        title: "Patterned Dress Shirt",
        img: "img/tshirt-man-6.jpeg",
        price: 15.95,
        info: "Patterned Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        block: 'today-2',
        identifier: '#216736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 501,
        title: "Premium Dress Shirt",
        img: "img/tshirt-man-7.jpeg",
        price: 21.95,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#217736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 502,
        title: "Premium Dress Shirt",
        img: "img/tshirt-man-8.jpeg",
        price: 19.95,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#218736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 503,
        title: "Premium Dress Shirt",
        img: "img/tshirt-man-9.jpeg",
        price: 15.95,
        info: "Premium Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#219736',
        sex: 'men',
        category: 'tshirt',
        sale: 'regular',
        collection: 'none',
    },
    
    // ================================================
    // Polo Men
    // ================================================

    {
        id: 7,
        title: "Patterned Dress Polo",
        img: "img/polo-man-1.jpeg",
        price: 49.95,
        info: "Patterned Dress Shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#721236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'new',
    },
    {
        id: 8,
        title: "River Island waffle polo",
        img: "img/polo-man-2.jpeg",
        price: 69.95,
        info: "River Island waffle polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#722236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 9,
        title: "Muscle fit jersey polo",
        img: "img/polo-man-3.jpeg",
        price: 45.95,
        info: "Muscle fit jersey polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#723236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 10,
        title: "Long sleeve tipped polo",
        img: "img/polo-man-4.jpeg",
        price: 52.95,
        info: "Long sleeve tipped polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#724236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 11,
        title: "Tonal batwing logo pique polo",
        img: "img/polo-man-5.jpeg",
        price: 33.95,
        info: "Tonal batwing logo pique polo in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#725236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 12,
        title: "Selected Homme polo shirt",
        img: "img/polo-man-6.jpeg",
        price: 38.95,
        info: "Selected Homme polo shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#726236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 13,
        title: "Crooked Tongues rugby polo",
        img: "img/polo-man-7.jpeg",
        price: 55.95,
        info: "Crooked Tongues rugby polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#727236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 14,
        title: "Fred Perry bomber collar polo",
        img: "img/polo-man-8.jpeg",
        price: 45.95,
        info: "Fred Perry bomber collar polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#728236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
        block: 'selected-3',
    },
    {
        id: 15,
        title: "Selected Homme knitted polo",
        img: "img/polo-man-9.jpeg",
        price: 75.95,
        info: "Selected Homme knitted polo cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#729236',
        sex: 'men',
        category: 'polo',
        sale: 'regular',
        collection: 'none',
        block: 'today-1',
    },

    // ================================================
    // Shirts Men
    // ================================================

    {
        id: 16,
        title: "Selected Homme knitted shirt",
        img: "img/shirt-man-1.jpeg",
        price: 35.95,
        info: "Selected Homme knitted shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#491832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 17,
        title: "Relaxed revere windowpane shirt",
        img: "img/shirt-man-2.jpeg",
        price: 38.95,
        info: "Relaxed revere windowpane shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#492832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 18,
        title: "Stretch skinny fit shirt",
        img: "img/shirt-man-3.jpeg",
        price: 69.95,
        info: "Stretch skinny fit shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#493832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 19,
        title: "Revere slub cotton shirt",
        img: "img/shirt-man-4.jpeg",
        price: 29.95,
        info: "Revere slub cotton shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#494832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 20,
        title: "Stretch slim fit work shirt",
        img: "img/shirt-man-5.jpeg",
        price: 49.95,
        info: "Stretch slim fit work shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#495832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 21,
        title: "Selected Homme organic cotton grandad",
        img: "img/shirt-man-6.jpeg",
        price: 42.95,
        info: "Selected Homme organic cotton grandad cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#496832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 22,
        title: "Skinny fit stripe shirt in navy",
        img: "img/shirt-man-7.jpeg",
        price: 38.95,
        info: "Skinny fit stripe shirt in navy cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#497832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 23,
        title: "Weekday Marwin Nylon short sleeve",
        img: "img/shirt-man-8.jpeg",
        price: 25.95,
        info: "Weekday Marwin Nylon short sleeve cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#498832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 24,
        title: "New Look long sleeve poplin shirt",
        img: "img/shirt-man-9.jpeg",
        price: 42.95,
        info: "New Look long sleeve poplin shirt cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#499832',
        sex: 'men',
        category: 'shirt',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Sweaters
    // ================================================

    {
        id: 25,
        title: "Knitted wide rib turtle sweate",
        img: "img/sweater-man-1.jpeg",
        price: 62.95,
        info: "Knitted wide rib turtle sweate cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#541832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 26,
        title: "Knitted wide-rib turtleneck sweater",
        img: "img/sweater-man-2.jpeg",
        price: 69.95,
        info: "Knitted wide-rib turtleneck sweater in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#542832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 27,
        title: "Selected Homme sweater in white",
        img: "img/sweater-man-3.jpeg",
        price: 49.95,
        info: "Selected Homme sweater in white in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#543832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 28,
        title: "Jack & Jones Essentials sweater",
        img: "img/sweater-man-4.jpeg",
        price: 65.95,
        info: "Jack & Jones Essentials sweater in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#544832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 29,
        title: "Muscle fit ribbed sweater in black",
        img: "img/sweater-man-5.jpeg",
        price: 35.95,
        info: "Muscle fit ribbed sweater in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#545832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 30,
        title: "River Island ribbed sweater",
        img: "img/sweater-man-6.jpeg",
        price: 45.95,
        info: "River Island ribbed sweater in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#546832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 31,
        title: "New Look crew neck sweater",
        img: "img/sweater-man-7.jpeg",
        price: 75.95,
        info: "New Look crew neck sweater in dark gray in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#547832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 32,
        title: "Knitted oversized textured yarn",
        img: "img/sweater-man-8.jpeg",
        price: 39.95,
        info: "Knitted oversized textured yarn in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#548832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 33,
        title: "River Island long sleeve knitted",
        img: "img/sweater-man-9.jpeg",
        price: 38.95,
        info: "River Island long sleeve knitted in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#549832',
        sex: 'men',
        category: 'sweater',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Overalls Man
    // ================================================

    {
        id: 34,
        title: "One Above Another denim jumpsuit",
        img: "img/overall-man-1.jpeg",
        price: 68.95,
        info: "One Above Another denim jumpsuit in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#511637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 35,
        title: "Denim short boilersuit in blue",
        img: "img/overall-man-2.jpeg",
        price: 79.95,
        info: "Denim short boilersuit in blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#512637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
        
    },
    {
        id: 36,
        title: "Denim overalls in dusky pink",
        img: "img/overall-man-3.jpeg",
        price: 49.95,
        info: "Denim overalls in dusky pink in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#513637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
        block: 'selected-2',
    },
    {
        id: 37,
        title: "Boilersuit in blue with pocket",
        img: "img/overall-man-4.jpeg",
        price: 59.95,
        info: "Boilersuit in blue with pocket in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#514637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 38,
        title: "Topman overalls in washed blue",
        img: "img/overall-man-5.jpeg",
        price: 54.95,
        info: "Topman overalls in washed blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#515637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 39,
        title: "Tall short boilersuit with cut",
        img: "img/overall-man-6.jpeg",
        price: 34.95,
        info: "Tall short boilersuit with cut in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#516637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 40,
        title: "Skinny overalls in black",
        img: "img/overall-man-7.jpeg",
        price: 64.95,
        info: "Skinny overalls in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#517637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 41,
        title: "Baggy denim overall in stone",
        img: "img/overall-man-8.jpeg",
        price: 59.95,
        info: "Baggy denim overall in stone in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#518637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 42,
        title: "Denim overalls in indigo length",
        img: "img/overall-man-9.jpeg",
        price: 51.95,
        info: "Denim overalls in indigo length in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#519637',
        sex: 'men',
        category: 'overall',
        sale: 'regular',
        collection: 'none',
    },
    
    // ================================================
    // Jackets Man
    // ================================================

    {
        id: 43,
        title: "Denim jacket with detachable fleece",
        img: "img/jacket-man-1.jpeg",
        price: 79.95,
        info: "Denim jacket with detachable fleece in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#531492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
        
    },
    {
        id: 44,
        title: "Pull&Bear denim jacket in brown",
        img: "img/jacket-man-2.jpeg",
        price: 71.95,
        info: "Pull&Bear denim jacket in brown in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#532492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
        block: 'today-3',
    },
    {
        id: 45,
        title: "Pull&Bear denim jacket in black",
        img: "img/jacket-man-3.jpeg",
        price: 46.95,
        info: "Pull&Bear denim jacket in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#533492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 46,
        title: "Commuter coat with contrast binding",
        img: "img/jacket-man-4.jpeg",
        price: 65.95,
        info: "Commuter coat with contrast binding in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#534492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 47,
        title: "DESIGN skinny western denim jacket in black",
        img: "img/jacket-man-5.jpeg",
        price: 56.95,
        info: "DESIGN skinny western denim jacket in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#535492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 48,
        title: "DESIGN skinny denim jacket in gray",
        img: "img/jacket-man-6.jpeg",
        price: 41.95,
        info: "DESIGN skinny denim jacket in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#536492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 49,
        title: "Pull&Bear denim jacket in mid blue",
        img: "img/jacket-man-7.jpeg",
        price: 47.95,
        info: "Pull&Bear denim jacket in mid blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#537492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 50,
        title: "DESIGN denim jacket in white with rips",
        img: "img/jacket-man-8.jpeg",
        price: 36.95,
        info: "DESIGN denim jacket in white with rips in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#538492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 51,
        title: "Bershka faux leather biker jacket",
        img: "img/jacket-man-9.jpeg",
        price: 39.95,
        info: "Bershka faux leather biker jacket in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#539492',
        sex: 'men',
        category: 'jacket',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Hoodies Man
    // ================================================

    {
        id: 52,
        title: "COLLUSION drop shoulder sweatshirt",
        img: "img/hoodies-man-1.jpeg",
        price: 29.95,
        info: "COLLUSION drop shoulder sweatshirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#361436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
        block: 'today-4',
    },
    {
        id: 53,
        title: "Vintage inspired oversized hoodie",
        img: "img/hoodies-man-2.jpeg",
        price: 32.95,
        info: "Vintage inspired oversized hoodie in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#362436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 54,
        title: "AllSaints Raven ramskull hoodie",
        img: "img/hoodies-man-3.jpeg",
        price: 41.95,
        info: "AllSaints Raven ramskull hoodie in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#363436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 55,
        title: "Oversized sweatshirt with split",
        img: "img/hoodies-man-4.jpeg",
        price: 45.95,
        info: "Oversized sweatshirt with split in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#364436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 56,
        title: "Sweatshirt with Los Angeles text print",
        img: "img/hoodies-man-5.jpeg",
        price: 29.95,
        info: "Sweatshirt with Los Angeles text print in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#365436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 57,
        title: "Oversized hoodie with t-shirt hem in red",
        img: "img/hoodies-man-6.jpeg",
        price: 39.95,
        info: "Oversized hoodie with t-shirt hem in red in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#366436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 58,
        title: "New Look hoodie in cream with taping",
        img: "img/hoodies-man-7.jpeg",
        price: 23.95,
        info: "New Look hoodie in cream with taping in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#367436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 59,
        title: "Teddy borg hoodie in khaki with rib",
        img: "img/hoodies-man-8.jpeg",
        price: 31.95,
        info: "Teddy borg hoodie in khaki with rib in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#368436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 60,
        title: "Iridescent patch crew neck sweatshirt",
        img: "img/hoodies-man-9.jpeg",
        price: 37.95,
        info: "Iridescent patch crew neck sweatshirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#369436',
        sex: 'men',
        category: 'hoodies',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Activewear Men
    // ================================================

    {
        id: 61,
        title: "Fast Running Fast shorts in gray",
        img: "img/activewear-man-1.jpeg",
        price: 32.95,
        info: "Fast Running Fast shorts in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#181436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 62,
        title: "Nike Soccer academy sweatpants in navy",
        img: "img/activewear-man-2.jpeg",
        price: 42.95,
        info: "Nike Soccer academy sweatpants in navy in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#182436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 63,
        title: "4505 icon training stringer tank",
        img: "img/activewear-man-3.jpeg",
        price: 26.95,
        info: "4505 icon training stringer tank in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#183436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 64,
        title: "ASOS Yoga dry hoodie in gray",
        img: "img/activewear-man-4.jpeg",
        price: 41.55,
        info: "ASOS Yoga dry hoodie in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#184436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 65,
        title: "Soccer FC box logo T-shirt in gray",
        img: "img/activewear-man-5.jpeg",
        price: 62.95,
        info: "Soccer FC box logo T-shirt in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#185436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 66,
        title: "Under Armour woven graphic short",
        img: "img/activewear-man-6.jpeg",
        price: 28.95,
        info: "Under Armour woven graphic short in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#186436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 67,
        title: "Adidas Training 3 stripe hoodie",
        img: "img/activewear-man-7.jpeg",
        price: 44.95,
        info: "Adidas Training 3 stripe hoodie in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#187436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 68,
        title: "Nike Basketball zip thru flight jacket",
        img: "img/activewear-man-8.jpeg",
        price: 57.95,
        info: "Nike Basketball zip thru flight jacket in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#188436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 69,
        title: "Nike Running Wild Element long sleeve",
        img: "img/activewear-man-9.jpeg",
        price: 68.95,
        info: "Nike Running Wild Element long sleeve in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#189436',
        sex: 'men',
        category: 'activewear',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Jeans Men
    // ================================================

    {
        id: 70,
        title: "Skinny jeans in vintage dark blue",
        img: "img/jeans-man-1.jpeg",
        price: 33.95,
        info: "Skinny jeans in vintage dark blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#121645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 71,
        title: "'Cigarette' skinny jeans in mid blue",
        img: "img/jeans-man-2.jpeg",
        price: 36.95,
        info: "'Cigarette' skinny jeans in mid blue in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#122645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 72,
        title: "Spray on 'vintage look' jeans with power",
        img: "img/jeans-man-3.jpeg",
        price: 43.95,
        info: "Spray on 'vintage look' jeans with power in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#123645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 73,
        title: "Iridescent patch crew neck jeans",
        img: "img/jeans-man-4.jpeg",
        price: 56.95,
        info: "Iridescent patch crew neck jeans in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#124645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 74,
        title: "Levi's skinny jeans in distressed",
        img: "img/jeans-man-5.jpeg",
        price: 31.95,
        info: "Levi's skinny jeans in distressed in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#125645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 75,
        title: "Jack & Jones Intelligence Liam skinny",
        img: "img/jeans-man-6.jpeg",
        price: 39.95,
        info: "Jack & Jones Intelligence Liam skinny in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#126645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 76,
        title: "New Look slim jeans in gray",
        img: "img/jeans-man-7.jpeg",
        price: 52.95,
        info: "New Look slim jeans in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#127645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 77,
        title: "Jack & Jones Intelligence Liam skinny",
        img: "img/jeans-man-8.jpeg",
        price: 35.95,
        info: "Jack & Jones Intelligence Liam skinny in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#128645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 78,
        title: "Skinny fit jeans in brick wall advanced",
        img: "img/jeans-man-9.jpeg",
        price: 31.95,
        info: "Skinny fit jeans in brick wall advanced in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#129645',
        sex: 'men',
        category: 'jeans',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Shorts Men
    // ================================================

    {
        id: 79,
        title: "ASOS DESIGN slim chino shorts in stone",
        img: "img/shorts-man-1.jpeg",
        price: 26.95,
        info: "ASOS DESIGN slim chino shorts in stone in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#261745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 80,
        title: "Converse Star Chevron archive shorts",
        img: "img/shorts-man-2.jpeg",
        price: 22.95,
        info: "Converse Star Chevron archive shorts in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#262745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 81,
        title: "Topman skinny denim shorts with rips",
        img: "img/shorts-man-3.jpeg",
        price: 29.95,
        info: "Topman skinny denim shorts with rips in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#263745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 82,
        title: "Under Armour woven graphic shorts",
        img: "img/shorts-man-4.jpeg",
        price: 31.95,
        info: "Under Armour woven graphic shorts in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#264745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 83,
        title: "New Look vertical stripe short in white",
        img: "img/shorts-man-5.jpeg",
        price: 21.95,
        info: "New Look vertical stripe short in white in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#265745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 84,
        title: "ASOS DESIGN skinny chino shorts",
        img: "img/shorts-man-6.jpeg",
        price: 25.95,
        info: "ASOS DESIGN skinny chino shorts in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#266745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 85,
        title: "New Look skinny denim shorts in gray",
        img: "img/shorts-man-7.jpeg",
        price: 19.95,
        info: "New Look skinny denim shorts in gray in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#267745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 86,
        title: "Topman shorts in gray stripe",
        img: "img/shorts-man-8.jpeg",
        price: 13.95,
        info: "Topman shorts in gray stripe in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#268745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 87,
        title: "Levi's lightweight walk shorts in muddy",
        img: "img/shorts-man-9.jpeg",
        price: 29.95,
        info: "Levi's lightweight walk shorts in muddy in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#269745',
        sex: 'men',
        category: 'shorts',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Pants
    // ================================================

    {
        id: 88,
        title: "Lockstock textured pants with elastic",
        img: "img/pant-man-1.jpeg",
        price: 39.95,
        info: "Lockstock textured pants with elastic in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#241475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 89,
        title: "Topman skinny smart pants in toffee",
        img: "img/pant-man-2.jpeg",
        price: 32.95,
        info: "Topman skinny smart pants in toffee in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#242475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 90,
        title: "ASOS DESIGN super skinny pants",
        img: "img/pant-man-3.jpeg",
        price: 27.95,
        info: "ASOS DESIGN super skinny pants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#243475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 91,
        title: "Bershka skinny checked pants in navy",
        img: "img/pant-man-4.jpeg",
        price: 35.95,
        info: "Bershka skinny checked pants in navy in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#244475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 92,
        title: "Selected Homme straight fit chino",
        img: "img/pant-man-5.jpeg",
        price: 44.95,
        info: "Selected Homme straight fit chino in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#245475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 93,
        title: "Only & Sons check pants in tapered",
        img: "img/pant-man-6.jpeg",
        price: 19.95,
        info: "Only & Sons check pants in tapered in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#246475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 94,
        title: "ASOS DESIGN super skinny smart pants",
        img: "img/pant-man-7.jpeg",
        price: 21.95,
        info: "ASOS DESIGN super skinny smart pants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#247475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 95,
        title: "ASOS DESIGN super skinny smart pants",
        img: "img/pant-man-8.jpeg",
        price: 39.95,
        info: "ASOS DESIGN super skinny smart pants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#248475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 96,
        title: "Lockstock cargo pants in black texture",
        img: "img/pant-man-9.jpeg",
        price: 31.95,
        info: "Lockstock cargo pants in black texture in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#249475',
        sex: 'men',
        category: 'pants',
        sale: 'regular',
        collection: 'none',
    },

    // ================================================
    // Joggers Men
    // ================================================

    {
        id: 97,
        title: "ASOS DESIGN oversized sweatpants",
        img: "img/jogger-man-1.jpeg",
        price: 39.95,
        info: "ASOS DESIGN oversized sweatpants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#421563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 98,
        title: "Organic tracksuit with striped rib",
        img: "img/jogger-man-2.jpeg",
        price: 44.95,
        info: "Organic tracksuit with striped rib in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#422563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 99,
        title: "Puma Rebel logo sweatpants in black",
        img: "img/jogger-man-3.jpeg",
        price: 31.95,
        info: "Puma Rebel logo sweatpants in black in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#423563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 100,
        title: "Originals Sweatpants with Embroidery",
        img: "img/jogger-man-4.jpeg",
        price: 28.95,
        info: "Originals Sweatpants with Embroidery in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#424563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 101,
        title: "Super skinny lightweight sweatpants",
        img: "img/jogger-man-5.jpeg",
        price: 31.95,
        info: "Super skinny lightweight sweatpants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#425563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 102,
        title: "Oversized tapered cargo sweatpants",
        img: "img/jogger-man-6.jpeg",
        price: 35.95,
        info: "Oversized tapered cargo sweatpants in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#426563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 103,
        title: "Topman pants with elasticated waistband",
        img: "img/jogger-man-7.jpeg",
        price: 25.95,
        info: "Topman pants with elasticated waistband in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#427563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 104,
        title: "Topman smart sweatpants with elastic",
        img: "img/jogger-man-8.jpeg",
        price: 19.95,
        info: "Topman smart sweatpants with elastic in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#428563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },
    {
        id: 105,
        title: "muscle tracksuit with rib in beige",
        img: "img/jogger-man-9.jpeg",
        price: 39.95,
        info: "muscle tracksuit with rib in beige in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
        identifier: '#429563',
        sex: 'men',
        category: 'joggers',
        sale: 'regular',
        collection: 'none',
    },

    // 




    // =====================================================================================
    //                    ************    Women's Products ***********
    // =====================================================================================

];


export const detailProduct = {
        id: 1,
        title: "T-Shirt Summer Vibes",
        img: "img/men-tshirt-1-details.png",
        price: 19.99,
        info: "White Summer Vibes T-shirt in the uiKit line with a colorful print. Made of jersey cotton. T-shirt fits perfectly with jeans, pants or shorts.",
        size: {
            s: 'S',
            m: 'M',
            l:'L',
            xl: 'XL',
            xxl: 'XXL'
        },
        inCart: false,
        count: 0,
        total: 0,
    };
    